### ISSUE TITLE
alvr_server fails to build when mold is used as rust's default linker

### ISSUE THREAD

**Issue by alkeryn** [alvr-org/ALVR#1684]
## Description

i have the following in my .cargo/config.toml
```toml
[target.x86_64-unknown-linux-gnu]
linker="/usr/bin/clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/mold"]
```
because of that building alvr failed, removing those flags fixed the issue, but it'd be neat to be able to link it with mold, maybe it's a mold issue though.

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environment

Arch linux lattest.

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
Arch Linux
