### ISSUE TITLE
Headset connected, black screen, but tracking data [Linux] [Oculus GO]

### ISSUE THREAD

**Issue by JacekJagosz** [alvr-org/ALVR#887]
TL:DR:
1. How can I enable more debug output, as right now I get no errors?
2. How can I build static FFmpeg when using `cargo build` and not `cargo xtask`? Maybe that will fix the problem

### Bug reports:

I launch ALVR, headset says "stream will start soon", after Steam Home launches I see it on the monitor, while the headset's display turns black. When I turn off Steam VR, the headset goes back to waiting for connection screen.
Sometimes it will get stuck on "stream will start soon", while sometimes left eye will go black, while the right one will switch to "waiting for server restart".
And through all that the head tracking works perfectly, on Windows it works flawlessly too.
There is no error in `alvr_session_log.txt` or when launching Steam through the command line.
I am trying to package it for Solus, here is my build script, based on the one from the [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=alvr):
``` yaml
builddeps  :
   - pkgconfig(ImageMagick)
   - pkgconfig(alsa)
   - pkgconfig(gtk+-3.0)
   - pkgconfig(libavformat)
   - pkgconfig(libdrm_intel)
   - pkgconfig(libunwind)
   - pkgconfig(vulkan)
   - pkgconfig(x264)
   - pkgconfig(x265)
   - cargo
   - llvm-clang-devel
   - llvm-devel
   - nasm
   - vulkan-headers
   - vulkan-tools
   - yasm
setup      : |
    #%patch -p1 < $pkgfiles/alvr.patch
    sed -i 's:../../../lib64/libalvr_vulkan_layer.so:libalvr_vulkan_layer.so:' alvr/vulkan-layer/layer/alvr_x86_64.json
    cargo fetch --locked --target "x86_64-unknown-linux-gnu"
build      : |
    export RUSTUP_TOOLCHAIN=stable
    export CARGO_TARGET_DIR=target
    export ALVR_ROOT_DIR=/usr
    export ALVR_LIBRARIES_DIR=$ALVR_ROOT_DIR/lib64/
    export ALVR_OPENVR_DRIVER_ROOT_DIR=$ALVR_LIBRARIES_DIR/alvr/
    export ALVR_VRCOMPOSITOR_WRAPPER_DIR=$ALVR_LIBRARIES_DIR/alvr/
    #cargo xtask build-server --release --bundle-ffmpeg
    ls -ltra
    cargo build --frozen --release -p alvr_server -p alvr_launcher -p alvr_vulkan-layer -p vrcompositor-wrapper
install    : |
    ls -ltra
    install -Dm755 target/release/alvr_launcher -t "$installdir/usr/bin/"
    # vrcompositor wrapper
    #install -Dm755 target/release/vrcompositor-wrapper -t "$installdir/usr/libexec/alvr/"
    install -Dm755 target/release/vrcompositor-wrapper -t "$installdir/usr/lib64/alvr/"

    # OpenVR Driver
    install -Dm644 target/release/libalvr_server.so "$installdir/usr/lib64/alvr/bin/linux64/driver_alvr_server.so"
    install -Dm644 alvr/xtask/resources/driver.vrdrivermanifest -t "$installdir/usr/lib64/alvr/"

    # Vulkan Layer
    install -Dm644 target/release/libalvr_vulkan_layer.so -t "$installdir/usr/lib/"
    install -Dm644 alvr/vulkan-layer/layer/alvr_x86_64.json -t "$installdir/usr/share/vulkan/explicit_layer.d/"

    # resources (presets + dashboard)
    install -d $installdir/usr/share/alvr/{dashboard,presets}

    install -Dm644 alvr/xtask/resources/presets/* -t "$installdir/usr/share/alvr/presets/"
    cp -ar alvr/dashboard $installdir/usr/share/alvr/

    # Misc
    install -Dm644 packaging/freedesktop/alvr.desktop -t "$installdir/usr/share/applications"

    install -d $installdir/usr/share/icons/hicolor/{16x16,32x32,48x48,64x64,128x128,256x256}/apps/
    # cp -r icons/* $installdir/usr/share/icons/

    install -Dm644 packaging/firewall/alvr-firewalld.xml "$installdir/usr/lib/firewalld/services/alvr.xml"
    install -Dm644 packaging/firewall/ufw-alvr -t "$installdir/etc/ufw/applications.d/"

    install -Dm755 packaging/firewall/alvr_fw_config.sh -t "$installdir/usr/lib/alvr/"


```

I expect the problem might be the FFmpeg, or maybe even Vulkan in some way. But at this point I don't know anymore how to diagnose further. How can I enable more debugging output or build static FFmpeg?
Any suggestions will be extremely welcomed!
#### Environement

Solus 4.3, Mesa 21.3.1, FFmpeg 4.4 (WITH vulkan support), vulkan-headers 1.2.189.1
AMD Ryzen PRO 4650G (Renoir, using its iGPU), RADV
ALVR 16.0.0 and NIGHTLY 2021.12.14, both compiled from source
SteamVR 1.12.04
